name: test-binder-flexrilog
# copied from ipyvue-flatsurf and all its dependencies installed.
channels:
  - conda-forge
dependencies:
  - python=3.9
  - sagelib
  - sympy
  - scipy
  - ipywidgets
  # Work around https://github.com/flatsurf/ipyvue-flatsurf/issues/38
  - notebook>=6.0.0,<6.3.0
  - matplotlib-base
  - jupytext
  - pip
  - pip:
    - flipper
    - jupyter_ui_poll >=0.2.1,<0.3
  