name: test-binder-flexrilog
# copied from ipyvue-flatsurf and all its dependencies installed.
channels:
  - conda-forge
dependencies:
  - python=3.9
  - sage
  - ipywidgets
  - matplotlib-base
  - jupytext
  - pip
  - pip:
    - jupyter_ui_poll >=0.2.1,<0.3
  